### ISSUE TITLE
[Solved] Profiler: flickering "last" and "calls" fields in GUI

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#109]
Hi @PiezPiedPy , first of all thanks for the great contribution, your profiler turns out to be quite useful :)

I have a question, however: Currently, only the "AVG" field in the profiler window is useful. The "LAST" field and the "CALLS" field shows a number only for a brief fraction of a second (too fast to read), otherwise they only show "ms" and "0":

![profiler-1](https://user-images.githubusercontent.com/173609/28499393-e93867fa-6fb4-11e7-881d-b0fab762664d.PNG)

Could you look into that?

**Comment by fat-lobyte** [comment]
Also, if it's not too hard, could you add a button or something to reset averages? Or should I create a new issue for that?

**Comment by PiezPiedPy** [comment]
Last shows the last recorded time and Calls shows the number of calls in the current frame, if an entry is not called in the current frame then Last and Calls will default to Zero which I assume causes the flicker.
 I will see if I can fix the flicker by leaving the Last and Calls field filled with the last value they received rather than blanking them out.
 If that does not solve the problem then I will add a display frame rate limiter as I did with the Gui.

I will also add an Avg Reset button for you, I like good ideas :)

**Comment by PiezPiedPy** [comment]
Reset button is done ;)

But looking at the Last and Call outputs after leaving the last values in place was giving a false view of what was happening with measured code, i.e. when an entry is not called you don't want the number of calls to show say 6 or 9 when in fact it is zero.

So I'm going to use a frame limiter instead to steady the display of the entries.

**Comment by PiezPiedPy** [comment]
I'm thinking about a radio button to disable the display of zero call entries, leaving the last value recorded still viewable.

**Comment by fat-lobyte** [comment]
> Last shows the last recorded time and Calls shows the number of calls in the current frame, if an entry is not called in the current frame then Last and Calls will default to Zero which I assume causes the flicker.

That would be a bit strange because I'm pretty sure that the profiled code is called in every single frame. I don't quite know why it wouldn't be called.
Second, 

> Reset button is done ;)

Wonderful, thank you :)

> So I'm going to use a frame limiter instead to steady the display of the entries.

What is better: display the calls in the last frame and keep the value fixed for a period of time (frame limiter) or better to display the calls since the last display change(in the last `update_fps` ms)? I don't know. What do you think?

Maybe an "avg calls per frame" field that behaves like the average time field would also be good.

**Comment by PiezPiedPy** [comment]
>That would be a bit strange because I'm pretty sure that the profiled code is called in every single frame. I don't quite know why it wouldn't be called.

I was thinking the same thing when I was testing but I didn't look at the cause of the problem, I just assumed the code wasn't called every frame. As for what is stopping the profiler from detecting the calls is a mystery to me, its either Unity, KSP or the Profiler itself that's causing the issue, or for some reason the code actually wasn't called!!

>What is better: display the calls in the last frame and keep the value fixed for a period of time (frame limiter) or better to display the calls since the last display change(in the last update_fps ms)? I don't know. What do you think?

I think it may be better to show calls since the last display change, but sometimes its good to know how many calls where made in the last frame, so I am now thinking to add both ideas.

>Maybe an "avg calls per frame" field that behaves like the average time field would also be good.

I like this idea so I'll implement it too.

**Comment by PiezPiedPy** [comment]
Solved the flickering issue, was due to a number of factors, mainly because I was updating the display via the FixedUpdate method, I'm such a plonker 😉
