### ISSUE TITLE
Update copyright and license notices

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#120]
We should go through the Code files and put the MIT license header on top of every file.
Also, we should put our names and years to each file that has been significantly altered.

**Comment by PiezPiedPy** [comment]
Sounds good too me

**Comment by PiezPiedPy** [comment]
I think maybe we should change the license to remove the option of a 3rdParty having resale rights etc.
The MIT license currently allows resale rights to 3rdParties which I don't think is a good idea.

I have only just recently changed the license regarding the New-GUI due to not wanting a 3rdParty to have rights to sell the work I have worked hard to create and think it would be a good idea to include the whole code base.

**Comment by Kerbas-ad-astra** [comment]
I would recommend against that particular choice of license.  I don't recognize the new license, but it is certainly not compatible with any extant permissible or Free Software licenses (which, by definition, do not have any restrictions based on the "identity" of the end user), so even though I (as a non-corporation) may have full rights to develop and contribute to your GUI code, I would not be able to apply anything I make from it into my other MIT- or GPL-licensed projects, so I have no incentive to contribute to it going forward. It's an evolutionary dead end in the broader Free Software ecosystem.

If you want to protect your work from corporate (or human) misbehavior, I would suggest the [**GNU General Public License**](https://www.gnu.org/copyleft/gpl.html).  It places no restrictions on who may use your software or how, but it requires that anyone who conveys your software (or a derivative work based on it) must provide source code and guarantee the same freedoms for their end users as you have guaranteed for yours (like a contractually-obligated "pay it forward" system).  I've written in much greater detail about software license selection [**on the KSP forum**](https://forum.kerbalspaceprogram.com/index.php?/topic/41210-license-selection-guide/&page=3&tab=comments#comment-1681967).

**Comment by PiezPiedPy** [comment]
#### I propose this as a draft for the License.txt file, basically the same as the MIT license but more restrictive regarding commercial use and resale by a 3rdParty but allows personal users the freedom to use Trajectories in for example videos on YouTube or Twitch with monetization etc:

`The Trajectories License.`

`©Copyright (c) 2014 Youen Toupin, aka neuoy`
`©Copyright (c) 2015 A.Korsunsky, aka fat-lobyte`
`©Copyright (c) 2017 S.Gray, aka PiezPiedPy`

`Any files, code, compiles, documentation etc. that are a part of the Trajectories`
`software ("the software") excluding 3rdParty files, code, compiles, documentation`
`etc. are subject to the following terms:`

`Any and all rights, assumed or otherwise, to the software are removed for any and`
`all persons, companies and/or corporations unless prior written authorization from`
`the copyright holders is given.`
 
`Any and all rights, assumed or otherwise, to any commercial or personal gain from`
`the use and/or resale of the software, not including personal user created content`
`from the use of the software, are removed unless prior written authorization from`
`the copyright holders is given.`

`Permission is hereby granted, for personal use only, free of charge, not for resale,`
`to any person wishing to use the software, including without limitation the rights`
`to use, copy, modify, merge, publish, distribute, create user content and/or`
`sub-license, subject to all the licence and copyright terms in this entire document.`

`The name of the copyright holders shall not be used in advertising or otherwise to`
`promote the sale, use, or other dealings without prior written authorization from`
`the copyright holders.`

`THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR`
`IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,`
`FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE`
`AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER`
`LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,`
`OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE`
`SOFTWARE.`

`This license and copyright notice shall be included and remain intact for all copies`
`and/or other works using the software except for personal user created content.`



#### It should suffice for all the source files in the project to only add a copyright and pointer to the license file such as:

`/*`
`©Copyright (c) 2014 Youen Toupin, aka neuoy`
`©Copyright (c) 2015 A.Korsunsky, aka fat-lobyte`
`©Copyright (c) 2017 S.Gray, aka PiezPiedPy`

`See the License.txt file for terms and conditions.`
`*/`

**Comment by PiezPiedPy** [comment]
@Kerbas-ad-astra thanks for the input I will give your post a read.

**Comment by PiezPiedPy** [comment]
The problem I have with the GPL License is it allows people/companies to charge for a copy of the software even if another person is offering the software for free, which is the whole reason why I don't want to use MIT or GPL, they are commercially friendly.

**Comment by Kerbas-ad-astra** [comment]
Like I said, by restricting the uses to which a person can apply software, your license is incompatible with MIT, Apache, and GPL, which locks it out of the majority of the ecosystem.  It might arguably be compatible with CC-BY-NC, but that has issues of its own (including that that license really shouldn't be used for software at all, but that's a different discussion), and is itself incompatible with those other licenses I mentioned (and the rest of the CC ecosystem, for that matter).

As to your second comment, it's true that a company could redistribute your GPL-licensed software for money, but they'd be competing against someone who's offering it for free.  They'd have to be adding something of value to the software if they wanted to stay in business.  If they're adding their own code, then by the GPL, they have to provide that code to the community (and you'd be free to make use of those code contributions yourself), so that's a win, or maybe they're supporting users who pay them (as e.g. Red Hat does with their distribution of Linux -- the software is free, but if a corporation wants to get their expertise for customization or installation support, that time costs money), which means people are getting help (which can be a bit of a grey area, but if it's not worth the price, nobody will pay it and the company loses money), so that's fine by me as well.  The GPL can't truly "prevent" corporate misbehavior (there's no "GNU Fairy" to stop bad behavior before it happens), but requiring a reciprocal guarantee of downstream user freedoms for the rest of the community blunts the worst behaviors I can think of, and if a corporation violates the GPL, there are organizations that will happily take up the cause of fighting them.

**Comment by fat-lobyte** [comment]
Here are my 2 cents on the situation:

First of all, we need to get @neuoy on board because he's still the biggest contributor and we can't just change the license without him. I think he should have the most say in the matter.

Second, I would really not devise an own License text. I'm not a lawyer, and there are already a myriad of licenses available to be copy-pasted. I think we should choose one of the standard licenses like MIT, GPL, Creative Commons, ...

> which is the whole reason why I don't want to use MIT or GPL, they are commercially friendly.

While the thought of companies making a buck off of our code makes me a bit uncomfortable, that is unfortunately what "open source" can entail. Freedom means freedom for everybody, including companies who want to sell your stuff. There's a good reason why [Debian](https://wiki.debian.org/DFSGLicenses) does not consider licenses to be "free software licenses" if they disallow commercial exploitation.

I think it's more important to protect the right to the source code and to modifications than excluding companies from selling it.

Now I think that MIT and Apache is a bit too laissez-faire, so I would prefer the GPL, but it may be worth looking into some of the Creative Commons ones because they seem to be a bit more "customizable".

**Comment by neuoy** [comment]
I'm fine to switch to GPL (or similar, i.e. copyleft)

As far as I know, you don't need my approval by the way ; I think previous versions keep the previous license, and the MIT allows to distribute under different licenses. GPL is more restrictive since it forces source code distribution for any derived work (copyleft).

I only think about two things to consider :

* Squad won't be able to embed the mod in the game if it's under GPL (unless they want to open source the whole game)
* People might distribute the mod for money (as already stated), misleading players into thinking this is the only way to get the mod (a practice that exists for various open source softwares). Since this is forbiden by Squad (I think ?) it should not be an issue here. Beside, as already stated above, "fixing" this issue would bring new issues.

**Comment by PiezPiedPy** [comment]
Since a new release is due for the KSP 1.4.1 update, I've changed the Trajectories license to GPL3.0 ready for the next release, as that license seems to be preferred by us and is more suitable for code than the Creative Commons license, which appears to be for music/art etc.
Also added copyrights to all the source code files.

I think we can probably close this issue now, unless someone wants to add something.

**Comment by neuoy** [comment]
That's fine for me, thanks :)

**Comment by fat-lobyte** [comment]
Thanks for the changes! Now I think we should mention it prominently in the changelog and in the release forum post, it is pretty relevant.

Since there are no more points to discuss, I am closing this issue as resolved. Thanks for all your participation! :)
