### ISSUE TITLE
KOS Cannot use Trajectories.

### ISSUE THREAD

**Issue by harrykirkwood** [neuoy/KSPTrajectories#131]
Using the latest version of KOS and Trajectories - upon using the KOS command 'PRINT ADDONS:TR:AVAILABLE.' It returns false meaning that KOS cannot access Trajectories,

**Comment by PiezPiedPy** [comment]
@harrykirkwood This is due to the changes made to the API in v.2 in PR #127 to help stop bugs like #124

I have left a PR on the kOS GitHub with the changes needed which they can merge into kOS for their next release.
https://github.com/KSP-KOS/KOS/pull/2220

It would be wise to leave an issue on the kOS GitHub with the problem your having, hopefully they will then include the changes required to kOS for their next release.

**Comment by PiezPiedPy** [comment]
Closed. kOS need to update their code to comply with the v.2 API
