### ISSUE TITLE
[Solved] Trajectory line is not displaying on the Map view [KSPv1.4 Testing]

### ISSUE THREAD

**Issue by PiezPiedPy** [neuoy/KSPTrajectories#139]
While testing a build for KSPv1.4, all seems to work fine except the rendering of the Trajectory line, Impact marker and Target marker in the Map view. No NRE's have reared their ugly heads and what is causing the issue is so far a mystery to me.
The In-Flight line is rendering fine which also suggests that the calculation of the Trajectory is also fine.
Target markers on the NavBall are working normally and all the NewGui functions also appear to be working.

**Comment by fat-lobyte** [comment]
\*sigh\* 😞 

The code for the map view trajectory is from an ancient version of RemoteTech, using direct OpenGL drawing calls and completely opaque to me.

You could try taking a look but at this point I think we might be better off reimplementing it.

**Comment by PiezPiedPy** [comment]
I'll try using something like you have with the In-Flight code using GLUtils, hopefully it will also be of use in the Map view.

**Comment by fat-lobyte** [comment]
Actually I would try to experiment more with the LineRenderer class that Unity provides, I think it improved since Unity 5.4. Either I have it lying around on a branch (for in-flight display) or we even shipped it at some point but took it out cuz the line looked weird.

I have assembled some links for myself, but might as well share them here:

https://unity3d.com/de/unity/whats-new/unity-2017.1.0
https://unity3d.com/de/unity/whats-new/unity-5.5.0
https://answers.unity.com/questions/1312246/how-to-set-startwidth-and-endwidth-of-linerenderer.html
https://answers.unity.com/questions/926128/keep-line-renderer-width-same-on-screen-no-matter.html
https://docs.unity3d.com/ScriptReference/LineRenderer-widthMultiplier.html
https://docs.unity3d.com/ScriptReference/LineRenderer-widthCurve.html
https://docs.unity3d.com/Manual/class-LineRenderer.html

The problem with GLUtils is that again, it is copy-pasted from another mod (MechJeb this time), uses direct OpenGL calls that I simply don't understand (I'm not a Graphics programmer, sorry). So I'm afraid it will be hard to maintain. If you want to take the time to dive into OpenGL I won't hold you back, but it will probably be a long and bumpy ride.

**Comment by PiezPiedPy** [comment]
I Played about with DirectX late 90,s early 2k's but only had a brief look at OpenGL. I would prefer to use Unity though, since that is what KSP uses.
Thanks for the links they will come in very handy 😉

**Comment by PiezPiedPy** [comment]
Kind of got this working by changing the camera listener from PreRender to PostRender but the Trajectory jumps about when the camera is moved, grrrrrr 😠

**Comment by PiezPiedPy** [comment]
Thanks to a post on the Trajectories KSP forum from Jebs_SY who suggested changing the render layer to 24 I have got this working now. I've got a few more changes to add before I commit, wont be long now until we can build a working release for KSP v1.4.1

**Comment by PiezPiedPy** [comment]
@fat-lobyte commits are in and ready to test, works fine on my system, just a small warning pops up in the Debug console, I think its something related to the Stock toolbar texture, I'll look into it at a later date.

Have you anything you want to add before release ?

**Comment by fat-lobyte** [comment]
Hey there, I've got nothing to add, so we're clear for release.

**Comment by PiezPiedPy** [comment]
All done here, so closing 😉

**Comment by PiezPiedPy** [comment]
@fat-lobyte Hi, I've just put together a branch for KSP v1.3.1 and cherry-picked needed commits.
I don't have KSP v1.3.1 installed to test and build a release, so I am hoping you still have v1.3.1 installed and could build the release for v1.3.1, all that needs doing is setting the date in the CHANGELOG.md file.

If not I can revert to v1.3.1 via steam but I am getting low on disk space so will be a bit of a headache for me to move between versions. (time for a new drive)

https://github.com/neuoy/KSPTrajectories/tree/KSP-v1.3.1-backport

Thought it would be better to start the branch now before too many commits for v.1.4.1 are in the master branch.

If the trajectory in the Map view does not display correctly in close zoom then the layer3D will need to be changed from layer 24 to 31 at this line.
https://github.com/neuoy/KSPTrajectories/blob/3afd63eee60c10b502467b03a715def214359859/Plugin/MapOverlay.cs#L66
