### ISSUE TITLE
Acting if it's installed but when its activated it wont work

### ISSUE THREAD

**Issue by Intragste** [neuoy/KSPTrajectories#190]
As said in the title, the mod will know that its installed but wont show up on blizzy's toolbar or when its activated through the menu it won't show up with the trajectory

**Comment by PiezPiedPy** [comment]
A log file would help

**Comment by Matthias199** [comment]
Agree same behavior I can aktivate the mod click at show trajectories, but there is no prediction !

[KSP.log](https://github.com/neuoy/KSPTrajectories/files/11524143/KSP.log)

**Comment by PiezPiedPy** [comment]
PlanetShine is spamming errors.

Trajectories reports 
[LOG 11:11:00.627] [Trajectories] v2.4.3 Starting
[ERR 11:11:00.631] [Trajectories] Error: Error creating config - Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown., usually caused by a mod failing to load before Trajectories loads

See Issue #183

**Comment by Matthias199** [comment]
so the solution would be to remove PlanetShine ?

**Comment by PiezPiedPy** [comment]
Maybe, depends if PlanetShine is the offending mod.

Read here for more info: https://github.com/neuoy/KSPTrajectories/blob/master/CONTRIBUTING.md#removing-mods-for-debugging
