### ISSUE TITLE
Exception when running Trajectories in KSP 1.1.3.

### ISSUE THREAD

**Issue by fat-lobyte** [neuoy/KSPTrajectories#72]
Hi, I'm getting the following exception when running Trajectories in KSP 1.1.3.

```
NullReferenceException: Object reference not set to an instance of an object
  at Trajectories.Trajectory.get_AerodynamicModelName () [0x00000] in <filename unknown>:0 

  at Trajectories.MapGUI.MainWindow (Int32 id) [0x00000] in <filename unknown>:0 

  at UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID) [0x00000] in <filename unknown>:0 

  at UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style) [0x00000] in <filename unknown>:0 
```

This happens after left-clicking the trajectories button repeatedly, until the button is pressed a second time.

The workaround is to use Blitzi's toolbar.

**Comment by neuoy** [comment]
bug not reproduced with the version I'm currently working on

**Comment by Artorp** [comment]
I'm getting the same exception, and the UI for Trajectories is glitched into a infinite height no width window. See attached screenshot. 
![trajectories](https://cloud.githubusercontent.com/assets/147366/18412294/f9979c88-778a-11e6-98d0-e5cdba81534b.png)

I'm running Trajectories v1.6.3

Exception from log:

```
[EXC 19:04:03.596] NullReferenceException: Object reference not set to an instance of an object  
	Trajectories.Trajectory.get_AerodynamicModelName ()  
	Trajectories.MapGUI.MainWindow (Int32 id)  
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
```


Full log file: http://pastebin.com/ka9YuLSR

It works fine with Blizzy's Toolbar, but not stock. I can upload savefile (and mods) if you'd like.

**Comment by neuoy** [comment]
Strange, I wasn't able to reproduce this one. Is it related to clicking the button as mentioned in the first post here?

**Comment by Artorp** [comment]
Yes, in my case it would spit out tons of exceptions when the window is shown on the toolbar, and none/be silent when it's inactive.

I'm running 64 bit Steam version of KSP btw, didn't check if it behaved differently on 32 bit.

Here's a savefile with a craft en route to Duna where I had this issue, not sure if the state of the mod is saved in the save file: https://dl.dropboxusercontent.com/u/14243021/Files/LaptopSave.zip

No mod with custom parts is used. Here's a modlist:

- AtmosphereAutopilot
- DockingPortAlignmentIndicator
- EasyVesselSwitch
- KerbalAlarmClock
- KerbalEngineer
- PreciseManeuver
- RCSBuildAid
- Trajectories
- TransferWindowPlanner

The button worked fine the first few times I used it. When it glitched out as I clicked the botton to activate it, the settings window was a 1x1px window which rapidly increased in height until it was in the state as in the screenshot.

Works fine in blizzy's, so there's something with the stock toolbar interaction.

**Comment by neuoy** [comment]
OK, I've found the issue. The bug happens if no trajectory is displayed when you load the game (i.e. "Display trajectory" is unchecked, and no target position is set). It does not happen if the game is already running when you uncheck "Display trajectory", but will happen next time you load the game and show the UI window. I don't think it's related to the toolbar (stock or Blizzy), but the steps to reproduce it are obscure enough to make it hard to spot what is or is not relevant (I had to look at the code to sort out what was happening).

I'll fix that in next release ; meanwhile, you can edit GameData\Trajectories\Plugin\PluginData\Trajectories\config.xml, and set DisplayTrajectories to 1 and you should be good to go. And don't uncheck "Display trajectory" until you have a fixed version (or don't forget to re-enable it before exiting the game).

**Comment by Artorp** [comment]
Awesome. Can confirm it works just fine if that option is set before launch. Look forward to the next release. Cheers!
