### ISSUE TITLE
Trajectories stops working after blank config.xml is written

### ISSUE THREAD

**Issue by EE-GSlomin** [neuoy/KSPTrajectories#73]
After reinstalling trajectories several times I figured out that an empty config.xml file was preventing the mod from working. Unfortunately reinstalling the mod doesn't overwrite this file at all. 

As a temporary fix I would suggest possibly adding a default config.xml to the mod download. I'm unsure what this would contain exactly.

**Comment by neuoy** [comment]
Hi,

I've had other reports of a corrupt XML config file, but this is weird because I don't understand when and why an erroneous file is written in the first place.

I could include a default file in the download, but this means everyone will loose their settings each time they upgrade the mod.

The XML file itself is written by KSP code, so I don't have control over what happens during load/save (I just have a save and load functions that I can call).

I think the best course of action to solve this issue would be to understand why the corrupt file is written, and solve that issue. Do you have any hint about what happened?

**Comment by EE-GSlomin** [comment]
I had a power outage while in the middle of a game. I had to restore my persistent safe file from the campaign I was playing as that was corrupted too. What is a bit of a mystery to me though is why the config for trajectories would be saved as a blank file at that point. 

Perhaps a better solution would be to write an exception handler for this case and rewrite the file then? I can post the specific stack trace I was getting a bit later.

**Comment by neuoy** [comment]
fixed in 1.6.3
