### ISSUE TITLE
Trajectories API not actually added

### ISSUE THREAD

**Issue by hvacengi** [neuoy/KSPTrajectories#74]
I'm in the process of attempting to merge the trajectories PR in kOS (https://github.com/KSP-KOS/KOS/pull/1603).  Before trying to get to the actual testing phase, I was trying to walk through all of the code to check some of the names and descriptions.  Which lead me to checking this repository itself.  It doesn't appear that the API PR (#67) updated the .csproj file to refer to API.cs, and when I add the reference manually the project won't build due to an unknown reference to `AutoPilot`.

As I'm not the person who initially submitted the PR ( @CalebJ2 ), I'm not entirely sure what class these methods should be referencing instead.  I suspect that the class got refactored between when the PR was originally authored and the PR was merged (or possibly after, since the project didn't know to update API.cs).  I have no issue submitting my own PR to fix the issue, but I need some guidance as to what classes should be reference instead.

**Comment by neuoy** [comment]
D'oh. You're right, the API.cs file is not included (don't know if it wasn't in the PR, or if I failed something when merging), and it references the now-removed AutoPilot class.

So now I won't be able to hide that I never even slightly tested anything about that API ;-)

I'll take a look about that broken AutoPilot dependency and probably commit the fixed project shortly.

**Comment by neuoy** [comment]
I've pushed the fix ; however I've not tested further than compilation. I hope it'll work as you expect ; let me know if it doesn't.

**Comment by hvacengi** [comment]
I will download, compile and test.  There's a chance I might need some clarification of terms thought.  The PR uses 3 different definitions for `CorrectedDirection` and I want to make sure it's explained correctly.  Are both "Planned" and "Corrected" based on the set target, or do they just align with the actual current projection?

**Comment by PBscoots** [comment]
I think "planned" is based on the actual current projection, and "corrected" is based on the set target. Planned seems to be what trajectories thinks is going to happen based based on your current Angle of Attack, and corrected is the current estimated trajectory PLUS the correction needed to get to the target you set. I think the intention for these is to be able to cross product them to zero in KOS for a steering control loop.
At least thats what it seems to be to me in the navballoverlay.cs file.

**Comment by PBscoots** [comment]
Maybe for clarity, the suffixes on the KOS side should be something like "currentdirection" for planneddirection and "targetdirection" for correcteddirection.

**Comment by neuoy** [comment]
"Planned" is the direction according to the planned AoA (angle of attack), which is configured in the descent profile (usually prograde for a spaceplane or retrograde for a capsule, but it can be fine tuned in the settings window). So for example if you configured a prograde entry, "PlannedDirection" will be exactly the direction of your current velocity.

"Corrected" is the same, but with an offset to try to reach the target. However it's really just an attempt, no simulation is made to see if it would work, and no calculation uses the actual vessel aerodynamic properties. Sometimes it's even steering in the wrong direction. It's as simple as "I'm going too short, I should pull up". More precisely, the direction goes toward up if the predicted crash site is too close (and toward down if it's too far) compared to the target point. This logic is reversed for retrograde reentries (AoA > 90°) because it works better this way for capsule. The farther away from the target point, the bigger the direction offset, to a maximum of 45°.
